name: qr_coder
description: "QR Code Generator"
publish_to: 'none'
version: 3.3.3+125

environment:
  sdk: '>=3.13.0 <4.0.0'
  flutter: '>=3.47.0'

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.6
  provider: ^6.1.5+1
  qr_flutter: ^4.1.0
  share_plus: ^12.0.0
  sqflite: ^2.4.3
  path: ^1.9.1
  intl: ^0.20.3
  mobile_scanner: ^7.4.0
  google_mobile_ads: ^6.0.0
  flutter_dotenv: ^6.0.1
  permission_handler: ^12.0.1
  device_info_plus: ^12.1.0
  image_gallery_saver_plus: 5.1.1
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  shared_preferences: ^2.5.5
  firebase_database: ^12.0.2
  linkable: ^3.0.2

  flutter_localizations:
    sdk: flutter
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_native_splash: ^2.4.8
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/img/
    - .env

flutter_native_splash:
  color: "#B39DDB"
  image: assets/img/splash_logo.png
  android: true
  ios: true
  fullscreen: true
