name: qr_coder
description: "QR Code Generator"
publish_to: 'none'
version: 3.2.0+120

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.3
  provider: ^6.1.2
  qr_flutter: ^4.1.0
  share_plus: ^10.0.0
  flutter_native_splash: ^2.4.0
  sqflite: ^2.3.3+1
  path: ^1.9.0
  intl: any
  mobile_scanner: ^5.1.1
  google_mobile_ads: ^5.1.0
  flutter_dotenv: ^5.1.0
  permission_handler: ^11.3.1
  device_info_plus: ^10.1.0
  image_gallery_saver_plus: ^4.0.1
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.4
  shared_preferences: ^2.3.2
  firebase_database: ^11.0.4
  linkable: ^3.0.2
  flutter_localizations:
    sdk: flutter
  url_launcher: ^6.3.0
  flutter_gen: ^5.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/img/
    - .env

flutter_native_splash:
  color: "#B39DDB"
  image: assets/img/splash_logo.png
  android: true
  ios: true
  fullscreen: true