// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaL96bVnF83IIsLxkFeXOsgFDq4RUZz_k',
    appId: '1:995734500990:web:411b7c0111e75681ccca2f',
    messagingSenderId: '995734500990',
    projectId: 'qrcoder-89c0f',
    authDomain: 'qrcoder-89c0f.firebaseapp.com',
    storageBucket: 'qrcoder-89c0f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZz3lyjh16Q7_Yd1j7tlVa07YPk9jhhhM',
    appId: '1:995734500990:android:7343a74650beb9d6ccca2f',
    messagingSenderId: '995734500990',
    projectId: 'qrcoder-89c0f',
    storageBucket: 'qrcoder-89c0f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFiQNYuAOkYv4YZ15ahznClOIglQSxPk4',
    appId: '1:995734500990:ios:b18e17dfa99a406accca2f',
    messagingSenderId: '995734500990',
    projectId: 'qrcoder-89c0f',
    storageBucket: 'qrcoder-89c0f.appspot.com',
    iosBundleId: 'com.example.qrCoder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFiQNYuAOkYv4YZ15ahznClOIglQSxPk4',
    appId: '1:995734500990:ios:b18e17dfa99a406accca2f',
    messagingSenderId: '995734500990',
    projectId: 'qrcoder-89c0f',
    storageBucket: 'qrcoder-89c0f.appspot.com',
    iosBundleId: 'com.example.qrCoder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaL96bVnF83IIsLxkFeXOsgFDq4RUZz_k',
    appId: '1:995734500990:web:f0895926e51924d4ccca2f',
    messagingSenderId: '995734500990',
    projectId: 'qrcoder-89c0f',
    authDomain: 'qrcoder-89c0f.firebaseapp.com',
    storageBucket: 'qrcoder-89c0f.appspot.com',
  );
}
